In [7]:
import transformers
from transformers import AutoTokenizer,AutoModelForSequenceClassification
import torch

In [6]:
checkpoint="distilbert-base-uncased-finetuned-sst-2-english"
tokenizer=AutoTokenizer.from_pretrained(checkpoint)
contexts=["Tesla investors back record-breaking Musk pay deal",
          "US tourist missing for days on Greek island"]
tokens=[tokenizer.tokenize(context) for context in contexts]
print(tokens)
ids=[tokenizer.convert_tokens_to_ids(token) for token in tokens]
print(ids)

[['tesla', 'investors', 'back', 'record', '-', 'breaking', 'mu', '##sk', 'pay', 'deal'], ['us', 'tourist', 'missing', 'for', 'days', 'on', 'greek', 'island']]
[[26060, 9387, 2067, 2501, 1011, 4911, 14163, 6711, 3477, 3066], [2149, 7538, 4394, 2005, 2420, 2006, 3306, 2479]]


In [12]:
id1=torch.tensor([ids[0]])
id2=torch.tensor([[2149, 7538, 4394, 2005, 2420, 2006, 3306, 2479]])
all_ids=torch.tensor([[26060, 9387, 2067, 2501, 1011, 4911, 14163, 6711, 3477, 3066], [2149, 7538, 4394, 2005, 2420, 2006, 3306, 2479,0,0]])
model=AutoModelForSequenceClassification.from_pretrained(checkpoint)

output_all=model(all_ids)
output_id1=model(id1)
output_id2=model(id2)
print(output_id1.logits)
print(output_id2.logits)
print(output_all.logits)

tensor([[ 2.6513, -2.0863]], grad_fn=<AddmmBackward0>)
tensor([[ 1.9396, -1.5433]], grad_fn=<AddmmBackward0>)
tensor([[ 2.6513, -2.0863],
        [ 1.8381, -1.5387]], grad_fn=<AddmmBackward0>)


In [16]:
all_ids

tensor([[26060,  9387,  2067,  2501,  1011,  4911, 14163,  6711,  3477,  3066],
        [ 2149,  7538,  4394,  2005,  2420,  2006,  3306,  2479,     0,     0]])

In [19]:
attention_mask=torch.tensor([[1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,0,0]])
outputs=model(all_ids,attention_mask=attention_mask)
model(outputs)

TypeError: tuple indices must be integers or slices, not tuple

In [21]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
sequences = ["I've been waiting for a HuggingFace course my whole life.", "So have I!"]

tokens = tokenizer(sequences, padding=True, truncation=True, return_tensors="pt")
output = model(**tokens)
print(outputs)

SequenceClassifierOutput(loss=None, logits=tensor([[ 2.6513, -2.0863],
        [ 1.9396, -1.5433]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)
